version: '3'
services:
  frontend:
    build:
      context: ./clientWeb
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./clientWeb:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
