version: '3'
services:
  frontend:
    hostname: frontend
    environment:
      - PORT=8080
    build:
      context: ./clientWeb
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./clientWeb:/app
    depends_on:
      - backend

  backend:
    hostname: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
