# Generated by Django 5.0.2 on 2024-02-11 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_jogadores', models.CharField(choices=[('5', '5 Jogadores'), ('6', '6 Jogadores'), ('7', '7 Jogadores'), ('8', '8 Jogadores'), ('9', '9 Jogadores'), ('10', '10 Jogadores'), ('11', '11 Jogadores'), ('12', '12 Jogadores')], max_length=2)),
                ('tipo_sorteio', models.CharField(choices=[('O', 'Ordem de chegada'), ('S', 'Sem sorteio'), ('N', 'Nivel Tecnico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placar', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('brasao', models.ImageField(blank=True, null=True, upload_to='brasao/')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peladas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('rating', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='players.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('I', 'Disponivel'), ('D', 'Disponivel'), ('P', 'Na pelada'), ('F', 'Removido')], max_length=1)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_partidas', to='players.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='players.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Pelada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('configuracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pelada', to='players.configuracao')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peladas', to='players.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('jogadores', models.ManyToManyField(related_name='times', to='players.jogador')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='players.pelada')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='players.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='vencedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencedor', to='players.time'),
        ),
    ]
